services:
  app:
    build: .
    container_name: integration
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ../:/app:cached
    tty: true
    networks:
      - scheduler

networks:
  scheduler:
    external: true
